### ISSUE TITLE
Error handler not used for invalid target values

### ISSUE THREAD

**Issue by lepinejf** [zenorocha/clipboard.js#142]
I wanted to test the error handler

````
clipboard.on('error', function(e) {
    console.error('Action:', e.action);
    console.error('Trigger:', e.trigger);
});
````

So I willingly targeted an invalid element inside the data-clipboard-target attribute.

Expected: Error would pass through the error handler
Result: Got this error instead: Uncaught Error: Invalid "target" value, use a valid Element

**Comment by zenorocha** [comment]
We have two different types of error handling.

The first one is based on what you pass in the constructor. As a developer, you have control over this part, that's why errors are thrown using `new Error()`.

The second one is based on the operation performed by the user. That means "did it worked or not?". On this case, we emit an error event.
