### ISSUE TITLE
Starting and trailing spaces in copied string Firefox 42 Windows 8

### ISSUE THREAD

**Issue by Creego** [zenorocha/clipboard.js#147]
It works normally in OsX, but on Windows starting and trailing spaces appear when string copied

**Comment by kafeltz** [comment]
Show us an online example! " string ".trim() could work on this anyway.

**Comment by zenorocha** [comment]
Exactly, just use `trim()` and you're good to go.

```
new Clipboard('.btn', {
    text: function() {
        return ' abc '.trim();
    }
});
```

**Comment by Creego** [comment]
I can`t show you example - project is in development now

I know about trim and already used it, just reported about this issue )

**Comment by zenorocha** [comment]
If trim doesn't work for you, please isolate your code on a JSFiddle and share with us.

**Comment by Creego** [comment]
No, it`s ok, it already worked when i opened this issue )

**Comment by kelvinatorr** [comment]
I ran into this problem on Firefox 75. It turns out, your HTML needs to only have the text you want to copy, no new lines or indentation for aesthetics.

So do this:
```
<p id="copyTarget">text you want</p>
```

Not this:
```
<p id="copyTarget">
    text you want
</p>
```
The copied string will no longer have leading and trailing spaces in both Chrome and Firefox.
Hopefully this saves someone some time.
