### ISSUE TITLE
Generate the content to copy programatically

### ISSUE THREAD

**Issue by fernandojsg** [zenorocha/clipboard.js#156]
Is there any way to generate the content I want to copy once I've clicked the copy button? Like providing a function to generate the content or something like this?

**Comment by zenorocha** [comment]
Yes, check the documentation at: https://clipboardjs.com/#advanced-usage

**Comment by micahstairs** [comment]
When I use a function instead of defining the text or target attributes, I get this error:

**Missing required attributes, use either "target" or "text"**

However, this method work when I return a string literal, but not when it returns a String object. Do you know what's going on?

 var clipboard = new Clipboard('.clipboard', {
    text: function(trigger) {
      // return "string"; // this one works
      return functionThatReturnsAString(); // this one doesn't work
  });
