### ISSUE TITLE
allow passing DOM element instead of selection string to constructor

### ISSUE THREAD

**Issue by alanhamlett** [zenorocha/clipboard.js#18]

**Comment by zenorocha** [comment]
Hey @alanhamlett,

Thanks for your suggestion. We started like this, but then we realized that it could be harmful for performance because we'd have to attach listeners for every single element passed. Instead we decided to use event delegation https://github.com/zenorocha/clipboard.js/commit/ced945f11ae152a8423dad6986dd30aeb784bd47 and that's why you need to pass a selector as a string.

**Comment by alanhamlett** [comment]
Oops, it's even in the readme. My bad :)

Sometimes it doesn't hurt to have the info twice, like in a Performance section for people who skim like me.

**Comment by zenorocha** [comment]
No problem :)
