### ISSUE TITLE
Feature request: clearing the clipboard after X seconds

### ISSUE THREAD

**Issue by nilsteampassnet** [zenorocha/clipboard.js#211]
Hello,

I've got no issue with this very good library ;)

I was just wondering if it could be improved by adding an option permitting to clear the clipboard after a certain number of seconds (after a copy in clipboard was done of course).
Ideally this time should be set into a parameter.

Thanks again and hoping my feature request has interest to you.

Greetings

Nils

**Comment by zenorocha** [comment]
Hey @nilsteampassnet, thanks for asking!

> Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. Which means that the first argument in the constructor is required and must refer to a valid element in the page. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. Which means that the first argument in the constructor is required and must refer to a valid element in the page. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations
