### ISSUE TITLE
[rant] This module's name is misleading

### ISSUE THREAD

**Issue by naturalist** [zenorocha/clipboard.js#212]
This module should be providing pure copy and cut  functions and let the user decide how to use them in their code. For example:

    copyToClipboard(text);
    cutToClipboard();

Instead, this module acts as a stupid jQuery plugin binding its whole existence to DOM elements and hiding the underlying functionality away from the user.

**Comment by zenorocha** [comment]
First of all, thank you for being so polite. I honestly couldn't care less about your opinion since you clearly didn't spend at least a minute reading the source code.

This an open source project and if you feel like it doesn't solve your problem, use another thing or create your own. Remember kid, **you're not obligated to use this**.
