### ISSUE TITLE
A couple of simple questions

### ISSUE THREAD

**Issue by franko** [zenorocha/clipboard.js#229]
I am using clipboard.js for a small project and I wish to thank you for that nice library.

I have two questions. I am trying to figure out how to trigger the copy action based on a key press event (ctrl-c). Up to know it seems to me that the copy action can be triggered only by an HTML element. How can you trigger a copy action using javascript code ?

Second question, I have a very simple use case for which even clipboard.js is overkill. What would be the bare minimum to push some program-generated string on the clipboard based on an arbitraty event ? I understood you use execCommand("copy") under the hood but I cannot figure how to push the text that I want into the clipboard. I precise that for my simple project I do not care about IE compatibility.

**Comment by zenorocha** [comment]
Unfortunately you can't achieve that with clipboard.js.

You're right about `execCommand("copy")`, that's the only thing you need besides a user interaction (due to security restrictions imposed by browser vendors). I recommend reading about this API at: http://www.sitepoint.com/javascript-copy-to-clipboard/
