### ISSUE TITLE
Copy on a specific event

### ISSUE THREAD

**Issue by MicroDroid** [zenorocha/clipboard.js#245]
Clipboard.JS should have a way to manually copy by code.
Simply I want to have a hotkey to copy some text, StackOverflow says I should use something like:

    $(window).keydown(function(e) {
        if (e.key == 67)
        // How do I copy my text here to the clipboard?
    }

**Comment by zenorocha** [comment]
Due to security restrictions imposed by browser vendors, user interaction is required in order for copy/cut to work. For example, a simulated click event using JavaScript would not work as this would enable clipboard poisoning. I'm afraid keydown events aren't allowed as well.

Feel free to use another library or `execCommand` directly.

**Comment by MicroDroid** [comment]
uh, then perhaps I'd have to wait a bit more still the W3 realizes that a Clipboard API should be a thing, or at least writing to it.

Thanks anyways

**Comment by kafeltz** [comment]
Some bot could auto answer this common question =D
