### ISSUE TITLE
False Advertising. There are dependencies to this project. 

### ISSUE THREAD

**Issue by AdamHess** [zenorocha/clipboard.js#248]
They just don't need to be included because they are wrapped up into a single file. 

It would be as if I said "had no dependency on jquery" but included the version of jQuery I wanted with no conflict enabled and set to a locally scoped variable. 

This project has two external dependencies: tiny-emitter and good-listener.

**Comment by zenorocha** [comment]
What I meant by "no dependencies" is that there's no framework dependency involved. No jQuery, React, Angular, Ember. If you take a look at the dependencies listed in package.json you'll see that they all were made by me, except for one (which I'll rewrite at some point). The only reason why they are in separate packages is because they are generic enough to help other people.

**Comment by FagnerMartinsBrack** [comment]
@zenorocha If possible, I would suggest create some action on these kind of feedback. In this case it might be useful to use "No vendor dependencies" or explaining what "no dependencies" mean in the docs. Probably most devs that read the docs are not aware that the "no dependencies" represent that there's no framework of library required for this, and most of them will not look for clarification in the issues.

The first thing one might think is that this kind of stuff is not important, but if we really want to make an impact and create something meaningful for everyone, sometimes it might be interesting to reduce the margin for interpretation in the docs.

This seems similar on two pieces of feedback [I received a few weeks ago](https://github.com/js-cookie/js-cookie/issues/189). That issue managed to receive a second feedback because the issue was kept open for sometime to see if someone was going to comment on it.

It was very useful for that project and I hope it can be useful here too 👍

**Comment by zenorocha** [comment]
@FagnerMartinsBrack I honestly think this is super irrelevant and has nothing to do with "impact" or "meaningfulness". There are tons of more important things to be done in this project (and in life).

Changing to "no frameworks" instead of "no dependencies".
