### ISSUE TITLE
Cmd + C doesn't work is Safari when selector is DOM element

### ISSUE THREAD

**Issue by zhukov** [zenorocha/clipboard.js#260]
### Minimal example

I've forked your jsfiddle: https://jsfiddle.net/zoawfsz1/

### Expected behaviour

In safari I press "Copy" button, then Cmd + C and expect it to copy "hello" text.

### Actual behaviour

It doesn't work, because fakeHandlerCallback gets called on the same click that triggered initial copy => fake element gets deleted from DOM before I can press CMD + C. I guess you can set the callback inside `setTimeout(..., 0)`.

### Browsers affected

Safari on OS X Version 9.1 (11601.5.17.1)

Not sure if `new Clipboard(buttonDomElement);` is currently supported, but it works perfectly except for this bug and it's the only nice way to work with e.g. Angular JS.

**Comment by zenorocha** [comment]
Hey @zhukov, thanks for reporting! I'm not sure how to solve this but since Safari 10 announced support for `execCommand('copy')` which is the API we use, I think we should be fine. In the meanwhile, I suggest you to use `data-clipboard-target` if you want a better experience on Safari since it shows the selected content.
