### ISSUE TITLE
Copy text from JavaScript string variabvle when my app triggers it to do so

### ISSUE THREAD

**Issue by jasondavis** [zenorocha/clipboard.js#273]
Is it possibble tocopy text to clipboard from a JavaScript variable holding a string of text and to have it happen when my app calls a function to do it instead of requiring a button or DOM element?

I have a bookmarklet which converts a GItHub file URL into a Rawgit.com URL.  I want to have the JS in the bookmarklet add that generated URL to the users clipboard.

**Comment by zenorocha** [comment]
You can copy a JavaScript variable holding a string by using the imperative API: https://github.com/zenorocha/clipboard.js#advanced-options

Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. A function call or simulated click event using JavaScript does not work as this would enable clipboard poisoning.
