### ISSUE TITLE
clipboard.js doesn't work in PhantomJS properly

### ISSUE THREAD

**Issue by APshenkin** [zenorocha/clipboard.js#279]
When you click on the button with clipboard.js in PhantomJS, text doesn't appears in the clipboard.

### Expected behaviour

After clicking on clipboard.js button the text copied to the clipboard

### Actual behaviour

Text doesn't appears in the clipboard. Only if after click you will press "ctrl + c", text will be copied

### Browsers affected

PhantomJS 2.1.1

Tested using

CodeceptJS + WebdriverIO + GhostDriver on this page https://clipboardjs.com/#example-action

Can you please help me to solve this issue?

**Comment by zenorocha** [comment]
Hey @APshenkin!

Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

So I don't think this can be solved :/ But if you have any ideas feel free to send a PR.
