### ISSUE TITLE
Why clipboard is blank?

### ISSUE THREAD

**Issue by we138** [zenorocha/clipboard.js#288]
Hi guys! I try to use clipboard.js and I stumbled with strange behavior. I have this
```
<a class="chosen-single" tabindex="-1">
     <span>foobar</span>
</a>
```

and this
```<button class="btn" id="copy-app-id" data-clipboard-target="a.chosen-single span">Copy</button>```

but when I click on the button, nothing happens. Clipboard is empty. How fix it? 

sorry for my bad English

**Comment by zenorocha** [comment]
Please share a JSFiddle, otherwise I cannot help. Thanks!

**Comment by vberkel** [comment]
@zenorocha my situation also produces a blank clip. The events output to console show correct Action, Text and Trigger but it clears the clipboard for me. 

I created a fiddle for you [https://jsfiddle.net/jfrwe4eh/1/](https://jsfiddle.net/jfrwe4eh/1/).  I'm guessing it's because of special characters.

**Comment by kafeltz** [comment]
Try to remove the **style="display:none"** from **textarea**, for me it looks like a security from browser.

Maybe you need to **position: absolute; left: bigNumber**

**Comment by vberkel** [comment]
You were right, that works. Thank you.

**Comment by zenorocha** [comment]
If you need to copy content but don't want to it to appear you can use `data-clipboard-text` https://github.com/zenorocha/clipboard.js#copy-text-from-attribute or the imperative API https://github.com/zenorocha/clipboard.js#advanced-options

**Comment by weaknetlabs** [comment]
Hello, I still seem to have this issue. It sometimes copies a TAB or other large single white-space, but mostly doesn't overwrite what's in the clipboard. The event handler is working and your code in the console shows everything just fine, (Action, Text, Trigger all report just fine from on.success()), but nothing goes into the clipboard. I thought that the clipboard mechanism in my computer was screwed up because of Chrome/sharing and restarted the app and then the machine, but still does not work. I have also tested Firefox and it also does not work.

**Comment by zenorocha** [comment]
@weaknetlabs please share a reproducible example using JSFiddle

**Comment by weaknetlabs** [comment]
@zenorocha Sorry, it was definitely my computers at home. At work, it's working just fine. I remotely cleared my cache at home and made sure my CloudFlare proxy was in developer mode, but still happens at home. But here at work, I did the same and it's working! Sorry for the false alarm and thanks for the quick response! I need to look into why the clipboard was not working from Chrome at home.

**Comment by zenorocha** [comment]
Cool, thanks for answering back!
