### ISSUE TITLE
Can I add a new onclick function to this button created?

### ISSUE THREAD

**Issue by pendave** [zenorocha/clipboard.js#394]
Hi, what I want is after I click this button, it handles a setTimeout function to change the location.

But it fails, maybe a conflict to your script.

What can I do?

```
place.outerHTML += '<button class="mybtn" data-clipboard-text="'+ myContent + '">Copy</button>&nbsp;&nbsp;';

var clipboard = new Clipboard('.mybtn');

clipboard.on('success', function(e) {
	console.log(e);
});

clipboard.on('error', function(e) {
	console.log(e);
});
```

**Comment by zenorocha** [comment]
Clipboard.js comes with a built-in event listener due to security restrictions imposed by browser vendors. User interaction is required in order copy/cut to work. 

Try using the [imperative API](https://github.com/zenorocha/clipboard.js#advanced-options) if you need to some operations before copying.
