### ISSUE TITLE
Clipboard JS won't copy if not activated via a click event

### ISSUE THREAD

**Issue by avi12** [zenorocha/clipboard.js#400]
### Expected behavior

I expect that no matter which event occurs, once I call the Clipboard() constructor and return a string value to the text() function, that I provide to the constructor via the 2nd parameter - the string will be copied.

However, I discovered that the Clipboard constructor is getting called only for the **click** event ([JSFiddle](https://jsfiddle.net/5kk0eysw/17/)).
If I listen to any other event (I tested the KeyPress event) - nothing will happen.

### Browsers affected

I tested only in Google Chrome stable 57.0.2987.133 (64-bit), Mozilla Firefox stable 52.0.2 (32-bit), Microsoft Edge 38.14393.0.0 (64-bit) and Internet Explorer 11.953.14393.0.

**Comment by zenorocha** [comment]
Hey @avi12, thanks for reaching out!

Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. Which means that the first argument in the constructor is required and must refer to a valid element in the page. You always need an event listener and that's why it's built-in. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.
