### ISSUE TITLE
Improve API: `clipboard.paste('my text')`

### ISSUE THREAD

**Issue by hackhat** [zenorocha/clipboard.js#405]
I wonder why do you need to attach to a dom element?

I would suggest to have an option without dom.

At the moment I'm thinking in wrapping your library to make it easier to use.

Thanks

**Comment by zenorocha** [comment]
Hello @hackhat!

Due to security restrictions imposed by browser vendors, user interaction is required in order copy/cut to work. A simulated click event using JavaScript does not work as this would enable clipboard poisoning.

Don't feel obligated to use clipboard.js though, do what you think it's best for your project :)

**Comment by hackhat** [comment]
Hi @zenorocha what I meant was that the end-user (the developer) might not always want to have a dom element to attach. You could do it behind the scenes by creating an element on the body and attach yourself?

**Comment by zenorocha** [comment]
Yes, that's what I do already: https://github.com/zenorocha/clipboard.js#copy-text-from-attribute but you still need an element to trigger because of this browser limitation.
