### ISSUE TITLE
Support for events besides click

### ISSUE THREAD

**Issue by gaastonsr** [zenorocha/clipboard.js#417]
Hi! I like clipboard.js a lot. I was wondering if you were thinking about adding support for events besides click?

**Comment by zenorocha** [comment]
Hey @gaastonsr, what other events would you like?

**Comment by gaastonsr** [comment]
I actually don't have a use case 😬

But I was thinking if we could do expose generic API it would be great. For example a copy function that takes a string and copies it to the clipboard.

I think it would clean the code in instances like with React where it's discouraged to tap into the DOM elements.

We could do things like

```jsx
import React, { PropTypes } from 'react';
import { copy } from 'clipboard';

function InvitationUrl(props) {
  return (
    <div>
      <div>Invitation url: {props.url}</div>
      <button onClick={()=> copy(props.url)}>Copy Url</button>
    </div>
  );
}

InvitationUrl.propTypes = {
  url: PropTypes.string,
};

export default InvitationUrl;
```

**Comment by zenorocha** [comment]
A copy function that takes a string and copies it to the clipboard would not be possible due to security restrictions imposed by browser vendors. User interaction is required in order copy/cut to work. A simulated click event using JavaScript does not work too as this would enable clipboard poisoning, that's why a DOM element with a click event listener is necessary.

There are some third-party wrappers for React that might be helpful for you.

https://www.npmjs.com/package/react-clipboard.js
https://www.npmjs.com/package/react-clipboard-icon
https://www.npmjs.com/package/react-clip

**Comment by gaastonsr** [comment]
Understood! thanks for the explanation.

**Comment by ryantheleach** [comment]
Will copying with a keypress work? e.g. ctrl+c
