### ISSUE TITLE
It doesn't work on iPhone with IOS10

### ISSUE THREAD

**Issue by zhanyuzhang** [zenorocha/clipboard.js#438]
My code as follows:
```
<!-- Target -->
<input id="foo" value="https://github.com/zenorocha/clipboard.js.git">

<!-- Trigger -->
<button class="btn" data-clipboard-target="#foo">
    <img src="assets/clippy.svg" alt="Copy to clipboard">
</button>

var clipboard = new Clipboard('.btn');

clipboard.on('success', function(e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

    e.clearSelection();
});

clipboard.on('error', function(e) {
    console.error('Action:', e.action);
    console.error('Trigger:', e.trigger);
});
```
It worked perfectly on desktop browser, but hit a problem that nothing happened on my iphone.

**Comment by zenorocha** [comment]
I've tested on iOS 10 and it works fine.

**Comment by simonseddon** [comment]
It doesn't work fine on iOS. Clearly there are some instances where it fails. I have it working fine on all browsers (including Safari desktop) but once I try it on iOS (actual iOS, not simulated) not only does it not work but it causes a fatal error which crashes all javascript on my site.

There are a lot of issues regarding iOS. Might be better to delve deeper rather than shutting them down without too much consideration?

**Comment by simonseddon** [comment]
I've just debugged my iPhone's Safari. **ReferenceError: Can't find variable: ClipboardJS**

This only seems to be present on the iPhone (X). Everything else I've tested (including Chrome on iOS works).

The example on clipboardjs.com, however, works a treat. So I've c/p the script in dist/clipboard.js.min from there and suddenly it works on all devices. So is something odd happening during webpacking or..? It's not like there's anything odd with my webpack (all other scripts in the bundle work and yours does too - except on iPhone).
