### ISSUE TITLE
can i just invoke a function instead of push a button to copy a text.

### ISSUE THREAD

**Issue by deejay-baddog** [zenorocha/clipboard.js#466]
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by deejay-baddog** [comment]
hi,Zeno Rocha. 
this project is great and very helpful. but after i read the code, i found that if i want to copy or cut, i have to click a button. can i just declare a function invoked it and passed the msg and then the copy is done.
im a new guy in JS and i realy dont know how to solve it. if you can tell me the possible way, it will be very greatful.

**Comment by joshuaptfan** [comment]
The basic JS method that this plugin relies on, [```document.execCommand()```](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard), requires that it be triggered by user interaction to prevent web pages from messing with the clipboard without the user's knowledge. This is a security feature and is enforced by every browser.

There is no way around this, but you *can* use JS to [simulate a button click](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) when you do something else. That "something else" must also be a user interaction though, but it can be as simple as the user focusing an element.

**Comment by deejay-baddog** [comment]
@joshuaptfan Thank you very much for guiding me. After i ask the question, I do try to simulate a button click event, and yes it worked. But it invoked the error callback, not the success. I dont know what did i miss.

**Comment by joshuaptfan** [comment]
Possibilities:

1. The first triggering event does not classify as a valid user interaction, so execCommand() failed due to security enforcement.
2. You "broke the link" between the valid triggering event and execCommand(), such that the browser does not associate the user interaction trigger with execCommand() for security enforcement.
3. Too much time passed between the triggering event and execCommand(), and it no longer counted as a ["short-lived event"](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard). Very unlikely unless you're doing some serious computation creating this lag.
4. You used the plugin improperly. You can try your luck [these pluginless methods](https://codepen.io/joshuaptfan/pen/PKqbRa) that do the same thing.

Troubleshooting is easy using the console (press F12), it will tell you where the error happened and why.

**Comment by deejay-baddog** [comment]
thank you @joshuaptfan.
I used these methods that you provided, and i think this function "copyText(text)" is exactly what i need. But i still can not copy the text. I opend the console, there was nothing errors here, and the code was actually executed. I dont know if there is any way to track it.

**Comment by joshuaptfan** [comment]
Use [breakpoints](https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints) or [```console.log()```](https://www.w3schools.com/js/js_output.asp) to see if the code is really being executed, or if there are no errors because the code didn't run.

```document.execCommand('copy')``` will do nothing if there is no text to copy. Make sure you are passing a string to ```copyText()```.

**Comment by Ruffio** [comment]
@joshuaptfan have you resolved your issue? Can this be closed?

**Comment by zenorocha** [comment]
Hey guys, I added a proposal for this feature. Can you check it out #518?

I'll close this issue for now and we move the discussion over there, ok?
