### ISSUE TITLE
This doesn't work in iframe? 

### ISSUE THREAD

**Issue by i9w** [zenorocha/clipboard.js#470]
This isn't working in iframe, tried adding the script in the iframe head tag, then using demo examples, the copy button doesn't do anything

**Comment by Ruffio** [comment]
Do you have a simple code sample that demonstrates the issue?

**Comment by Ruffio** [comment]
@i9w any sample code?

**Comment by zenorocha** [comment]
Thanks @Ruffio for asking these questions.

**Comment by iRonJ** [comment]
I have an iframe in an iframe on mobile and I’m potentially seeing this same issue

**Comment by iRonJ** [comment]
To clarify the events are triggering and I see the correct text being identified in the console but I’m getting a blank clipboard.

**Comment by hobri** [comment]
Why was this closed? It simply doesn't work for iframes, where the selector probably needs to append .contentDocument? I've tried:

```javascript
var clip = new ClipboardJS('button', {
    container: document.getElementById('#target').contentDocument
});
```

But that doesn't seem to work. Can we re-open and address this? Thanks!

**Comment by Ruffio** [comment]
iframe? Isn't that outdated? At stackoverflow I found this: https://stackoverflow.com/a/1088569

Try to use that

**Comment by alejandroiglesias** [comment]
I have an app running on an iframe that needs to copy either parent URL (`document.referrer`) or another string. When I use the app directly (ie, without being embedded with an iframe), it copies fine, but when the app runs inside the iframe, it doesn't.
Can you people please help me solve it? Is it possible?

**Comment by chevonc** [comment]
I have this same issue. Could we please re-open? I'm running an panel window of my main app in a seprate child window. This fails to work because the check here - https://github.com/zenorocha/good-listener/blob/master/src/is.js#L9

`value instance of HTMLElement` will only return true for elements create by the window in scope.` This causes clipboardjs to throw `First argument must be a String, HTMLElement, HTMLCollection, or NodeList` when constructing with an dom ref from another frame. If we could amend this check some how, that'd be great.

See here for why that check fails - https://stackoverflow.com/questions/384286/how-do-you-check-if-a-javascript-object-is-a-dom-object#comment12920435_384380

**Comment by leewisestamp** [comment]
So this still isn't possible?

**Comment by glassdimlygr** [comment]
Yeah I caught this problem. There would be ways around it, but for me it was a nice-to-have.

**Comment by sebalis** [comment]
Hi @zenorocha, could you please reopen this? Some code was provided by @derender and even with the change suggested by @Ruffio – using ```iframe.contentDocument || iframe.contentWindow.document``` – it is not working. If you want complete code, here is a minimal file (zipped to make Github accept the attachment): I have created an IFrame and filled it using the open method, then added buttons to try three ways of copying the Iframe content. The first button simply copies the empty IFrame element without content. The second (using the content document as a target) throws an error. The third (using the HTML element within the content document as a target) reports success but noting is copied. Tried in current versions of Chromium and Firefox under Linux.

[clipboardjs-iframe.html.zip](https://github.com/zenorocha/clipboard.js/files/6558113/clipboardjs-iframe.html.zip)
