### ISSUE TITLE
Mac OS Chrome scroll up :/

### ISSUE THREAD

**Issue by daykkin** [zenorocha/clipboard.js#502]
Hello! I have last version Mac OS / Chrome and clipboard.js (download today)
And unfortunately page scroll to top when i click the button.
Safari/Opera/Firefox/iPad/iPhone and etc didn't have this problem. Only Chrome.
Mobile devises (iPad/iPhone) have some glitch when i click the button and start scroll by myself. But it is not so horrible like Chrome automatic scroll on top.

**Comment by daykkin** [comment]
one clarification. it happening if i use clipboard.js into fancybox popup. like that: 
> var clipboard = new Clipboard('.js-tooltip-link', { container: document.getElementById('222') });

if i use it on page without popup and call clipboard like that:
> var clipboard = new Clipboard('.js-tooltip-link');
page not scroll to top and all seems ok.

How can i fix event in popup using?

**Comment by daykkin** [comment]
How i see in FF on Windows, and Chrome on MacOS, scroll thing exist like focus on new hidden textarea. And if in FF it scrolls to the bottom from my copylink that in Chrome scrolls go on top of a page. 
Any suggest?

**Comment by zenorocha** [comment]
Hey @daykkin, we need a minimal working example that demonstrates this problem, otherwise it's impossible to debug this on the dark.

**Comment by daykkin** [comment]
@zenorocha I'am sorry, in a middle on this page http://dev-digiair.ru/tessmart/item.php we have red copylink "www.tssmrt.ru/stretchjakkard" and its work like a charm. But if we open any item popup on this page (click any small circle photo), we see all previously described problems with copylink (mac os chrome, windows FF). And one more, in IE11 on Windows when we click to copylink - anchor just hided.
Thanks for your time!

**Comment by zenorocha** [comment]
When I say a minimal example I mean this: https://stackoverflow.com/help/mcve

There's a lot of code it's not related to clipboard.js which can be conflicting this behavior. We need to isolate everything in order to see if the problem is really here.

**Comment by andri** [comment]
I'm having this problem as well. My setup is minimal and using the data attributes like so:

`<a href="#" class="btn btn-copy" data-clipboard-target="#comp-form-text" title="Copy"><i class="material-icons">content_copy</i></a>`

Page jumps to the tp everytime.

**Comment by markadrake** [comment]
Hi @andri. 

Because you are using an anchor tag element with `href="#"` and getting the behavior you are describing - I'm going to assume that clipboard.js does not call `event.preventDefault()`. What happens here is the link will cause the browser to scroll to the top of the page (or if something more was provided, it would try to find that element). This is [standard behavior as described by W3C](http://www.w3.org/TR/html5/browsers.html#scroll-to-fragid). 

I'm very opinionated so I'm going to give you my suggestion - don't use anchor links this way. At it's best it's confusing, at it's worst it could present accessibility issues. Try using a button instead. And you could apply styling to the button to make it appear however you like.

If you still want to go with an anchor link, set the href attribute to something that does not exist such as `href="#!"`.

**Comment by zenorocha** [comment]
Thanks for helping out @markadrake!
