### ISSUE TITLE
Fails with new browsers (firefox/chrome)

### ISSUE THREAD

**Issue by JohnBergman** [zenorocha/clipboard.js#522]
### Minimal example

In a javascript

      //-- Is the clipboard supported?
      if(Clipboard.isSupported()) {
        $(".__ClipboardCopy").show();
      }
      else {
        $(".__ClipboardCopy").hide();
      }

      //-- Connect to any copy buttons...
      this.theClipboard = new Clipboard('.__ClipboardCopy');

In the html:

<a class="__ClipboardCopy" data-clipboard-action="copy" data-clipboard-text="http://localhost/hubs/nomads/content-contributors-nomads/danica-dudes/videos/traveling-back-in-fly-fishing/"><i class="far fa-copy mt-1"></i></a>

### Expected behaviour

Clicking on the resulting link does not copy the text into the clipboard.

When I connect toe success event, I see the values all present correctly. regardless of the browser

### Actual behaviour

It fails silently (meaning everything appears to work, however the text being copied never shows up in the clipboard.

### Browsers affected

Doesnt work in Firefox 58.0.1 64 bit.
Doesnt work in Chrome Version 63.0.3239.132 (Official Build) (64-bit)

Works with Edge and IE.

**Comment by frodopwns** [comment]
This fails for me in Chrome Version 63.0.3239.132 (Official Build) (64-bit) but works in Safari Version 11.0.3 (12604.5.6.1.1).

**Comment by zenorocha** [comment]
Hey @JohnBergman @frodopwns @josephfusco, @jlahijani, @hannesb, @philcook, @carlosgomez2, @brucek @christianseel, I need your help to understand the real problem here.

I opened clipboardjs.com on the following browsers and ran `Clipboard.isSupported()` on the console, here's the result:

Do you get something different than this?

<img width="1440" alt="screen shot 2018-02-28 at 4 12 52 pm" src="https://user-images.githubusercontent.com/398893/36820362-4ee19e56-1ca2-11e8-9489-c0ab536c190a.png">

<img width="1440" alt="screen shot 2018-02-28 at 4 14 48 pm" src="https://user-images.githubusercontent.com/398893/36820406-8881f462-1ca2-11e8-8c00-6b2759609ff5.png">

<img width="1440" alt="screen shot 2018-02-28 at 4 11 57 pm" src="https://user-images.githubusercontent.com/398893/36820367-53efbacc-1ca2-11e8-998e-0137a8c5bb9b.png">

<img width="1440" alt="screen shot 2018-02-28 at 4 13 52 pm" src="https://user-images.githubusercontent.com/398893/36820378-62b6a87c-1ca2-11e8-8367-cf0dc1f34f6d.png">

<img width="1440" alt="screen shot 2018-02-28 at 4 13 47 pm" src="https://user-images.githubusercontent.com/398893/36820384-69775738-1ca2-11e8-9e5e-c14df3dd1e00.png">

**Comment by hannesb** [comment]
Might be related to this problem: If you use jQuery dialogs, you have to set the container property in the Clipboard constructor to an element of the dialog. If you stay with the default behavior (container set to document.body), execCommand('copy') will not work with some browsers.

That's what I found out when trying to use clipboard.js with [Serenity](http://serenity.is/) (great platform btw.)

**Comment by frodopwns** [comment]
Problem turned out to be model window specific for me. Solved here: https://github.com/zenorocha/clipboard.js/pull/368.

**Comment by zenorocha** [comment]
Got it. In that case, I'm going to close this issue. Thanks guys!
