### ISSUE TITLE
Unable to copy from changed data-clipboard-text

### ISSUE THREAD

**Issue by Ruprect** [zenorocha/clipboard.js#566]
### Minimal example

https://jsfiddle.net/Ruprect/zbpxndoy/

### Expected behaviour

I update the data-clipboard-text when text changes in the form field, but regardless - It copies the placeholder text it starts with.

### Actual behaviour

Instead of a concatenation of data-url-prefix + text : "https://www.example.com/full/url/slug/to-a-page" I get "placeholder" which is default text in data-clipboard-text.

### Browsers affected

Chrome + Edge

**Comment by pedroabreu** [comment]
The issue here is related to jQuery. It seems that the `data` doesn't actually change the value in the DOM, hence clipboard only pics up `placeholder`. 

From a quick look at the docs, I couldn't actually find a reasoning for this behaviour but it seems that the goal is to create some sort of map in memory (and not the DOM)

Use `attr(data-whatever, value)` to update the attribute and it works

Updated jsfiddle: https://jsfiddle.net/zbpxndoy/17/
