### ISSUE TITLE
How to copy arbitrary text from js

### ISSUE THREAD

**Issue by Dieldore** [zenorocha/clipboard.js#654]
You haven’t written in the documentation how to make the text '123', for example, be copied to the clipboard from js, without html

**Comment by zhangchenglin** [comment]
https://github.com/zenorocha/clipboard.js/blob/master/demo/

**Comment by julienlafont-tabmo** [comment]
Could you be more specific?
I don't see any way to copy an arbitrary text, without referering to any DOM element, in these exemples.

What Dieldore want to do doesn't seems possible for what I see.

Something like `new ClipboardJS().copy("hello")`

**Comment by carpii** [comment]
You can copy arbitrary text using 

````
var clipboard = new ClipboardJS('.btn', {
        text: function() {
            return 'to be or not to be';
        }
    });
````

But it still needs a DOM element to trigger the copy.

I think what you're asking for is unfettered access to read the ClipBoard, without it being triggered by a user action.
I may well be wrong, but I'm guessing this is not possible due to the sandbox permissions (otherwise a rogue script could just copy potentially sensitive data and submit it via ajax)

**Comment by julienlafont-tabmo** [comment]
> I may well be wrong, but I'm guessing this is not possible due to the sandbox permissions (otherwise a rogue script could just copy potentially sensitive data and submit it via ajax)

It works with the following code (need to be improved, but works fine):

```
placeholder = document.createElement('textarea');
document.body.appendChild(placeholder);
placeholder.value = "to be or not to be";
placeholder.select();
document.execCommand('copy');
document.body.removeChild(placeholder);
```

**Comment by zenorocha** [comment]
`execCommand` which is the browser API we use behind the scenes, requires real user interaction, that's why we have DOM elements and events attached to it.
