### ISSUE TITLE
Provide clipboard-action as a separate library

### ISSUE THREAD

**Issue by sameoldmadness** [zenorocha/clipboard.js#66]
In some cases event capturing may be handled by the application itself, so it would be handy to directly create ClipboardAction with captured event.

**Comment by zenorocha** [comment]
Hey @sameoldmadness,

We don't have plans to expose ClipboardAction. This would cause more confusion than actually help because we'd need to document all parameters that are passed to that class.

If you still can't have the event handled by this lib, you have two options:

1) Fork this project and build ClipboardAction;
2) Clone this project, import the ClipboardAction and build it inside your project;

Thanks!
