### ISSUE TITLE
a function

### ISSUE THREAD

**Issue by StephenWu5** [zenorocha/clipboard.js#712]
可以实现复制css伪元素的内容吗？兄弟！ if you can,t see my word, use google translate

![image](https://user-images.githubusercontent.com/32475322/101237493-356ad700-3714-11eb-8f52-2402c3b4f9a5.png)

**Comment by StephenWu5** [comment]
are you here!

**Comment by vitormalencar** [comment]
Hi 👋🏾 @StephenWu5 if I understood correctly you want to copy the "content" of a pseudo-element
if you meant that you want to copy the `HTML` content of a pseudo-element then is not possible since pseudo-elements as far as I know are only able to hold CSS values

if you want to copy the `CSS` values of a pseudo-element you can use something like: 

```js 
window.getComputedStyle(element, "selector")
``` 

https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

to get the computed `CSS` values of the pseudo-element and then you can pass this value to the copy function

Please let me know if this answers your question.

**Comment by helderburato** [comment]
> Hi 👋🏾 @StephenWu5 if I understood correctly you want to copy the "content" of a pseudo-element
> if you meant that you want to copy the `HTML` content of a pseudo-element then is not possible since pseudo-elements as far as I know are only able to hold CSS values
> 
> if you want to copy the `CSS` values of a pseudo-element you can use something like:
> 
> ```js
> window.getComputedStyle(element, "selector")
> ```
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
> 
> to get the computed `CSS` values of the pseudo-element and then you can pass this value to the copy function
> 
> Please let me know if this answers your question.

Did it help you @StephenWu5?
