### ISSUE TITLE
Event action is now a function not a string

### ISSUE THREAD

**Issue by pythonandchips** [zenorocha/clipboard.js#792]
## 🐛 Bug Report

Event action parameter used to return a string but now returns a function. The JSFiddle below demonstrates the change. 

> [JSFiddle](https://jsfiddle.net/g1d4tqps/) 

### Expected Behaviour

From the JSFiddle above expect e.action to equal "copy"

### Actual Behaviour

Instead of `e.action` being a string a function is returned

### To Reproduce

On [JSFiddle](https://jsfiddle.net/g1d4tqps/) click copy button.
Check console, expected string to be logged but is function.

### Browsers Affected

All

### Operational System

MacOS, Windows, Linux

**Comment by obetomuniz** [comment]
Thanks for report this bug @pythonandchips. I was able to reproduce on my side the same. I'll push a fix today or tomorrow for it.

**Comment by obetomuniz** [comment]
Hey @pythonandchips, now you can check on this [JSFiddle](https://jsfiddle.net/p8rguqa0/) the Event API working as expected after being fixed in [v2.0.10](https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.10). Thanks again for the report. 

Let us know if anything else does not work as expected. Thanks!

**Comment by pythonandchips** [comment]
@obetomuniz Thanks you very much

**Comment by Victoriacsl** [comment]
Hey @pythonandchips, The bug still exists。
