### ISSUE TITLE
"Invalid "target" value, use a valid Element" when using React

### ISSUE THREAD

**Issue by mrichman** [zenorocha/clipboard.js#809]
I've had success with this component before, but this is my first time tying it with React. When I click my Copy button, I get the error "Invalid "target" value, use a valid Element". Also the `clipboard.on("error"...` handler doesn't fire.

Here's my (abbreviated) code:

```javascript
import {
  Button,
  Container,
  Header,
  SpaceBetween,
} from "@awsui/components-react";

import ClipboardJS from "clipboard";

import "../styles/customer.scss";

function toCommaSeparatedList(serviceList) {
  const last = serviceList.pop();
  const result = serviceList.join(", ") + ", and " + last;
  return result;
}

function htmlID(name) {
  return "customer-" + name.replace(/[\W_]+/g, "");
}

function Customer(props) {
  // Copy to clipboard
  var clipboard = new ClipboardJS(".btn-clipboard");
  clipboard.on("success", function (e) {
    let customer = e.trigger.attributes["data-customer"].value;
    alert(
      `Copied content for ${customer} to clipboard! You may now paste it into your email.`
    );
    e.clearSelection();
  });
  clipboard.on("error", function (e) {
    console.error("Action:", e.action);
    console.error("Trigger:", e.trigger);
  });

  return (
    <Container
      header={
        <Header
          variant="h1"
          actions={
            <SpaceBetween direction="horizontal" size="xs">
              <Button
                variant="primary"
                iconName="copy"
                data-customer={props.Name}
                data-clipboard-target={htmlID(props.Name)}
                className="btn-clipboard"
              >
                Copy
              </Button>
            </SpaceBetween>
          }
        >
          {props.Name}
        </Header>
      }
      footer={<a href="#top">Back to top of page</a>}
    >
      <div id={htmlID(props.Name)}>
          THIS CONTAINS THE CONTENT I WISH TO COPY
...
```

**Comment by obetomuniz** [comment]
Hey @mrichman, thanks to bring the issue for us. I'll try to figure out the problem related to the usage of the lib with React.

Checking the code provided, did you passed a `#` as a prefix on `data-clipboard-target` declaration in order to declare to ClipboardJS the **intent to use the element id** of the target to create a link between the library and the element? For instance:

```jsx
<Button
   ...
   data-clipboard-target={`#${htmlID(props.Name)}`} // <-- notice the # as a prefix
   ...
>
 Copy
</Button>

<div id={htmlID(props.Name)}>
  THIS CONTAINS THE CONTENT I WISH TO COPY
</div>
 ```

Given the nature of the error reported, it seems the origin of the problem. 

Let me know if it works. If not, in the next few days I'll recreate a demo using React + Clipboard.js to check the current interoperability of both and help you reach a stable usage.

**Comment by obetomuniz** [comment]
Hey @mrichman. As promised, [here](https://codesandbox.io/s/adoring-tu-ukbqrd) is a demo using the suggestion that I mentioned. It works perfectly. Closing the issue for now since it is not related to the library. Feel free to re-open later if more details come.
