### ISSUE TITLE
Great project but where is react documentation?

### ISSUE THREAD

**Issue by encryptblockr** [zenorocha/clipboard.js#815]
Documentation is not very clear
How do we use this within react?
How do we call the package within react? 
No mention of this

**Comment by obetomuniz** [comment]
Hi @encryptblockr - Thanks for bringing up this suggestion. As it is today, the project doesn't have and needs any official port for React since there's nothing specific about setting up this library with React. Could you share if you're having problems connecting both? If so, I will use it to enhance a Troubleshooting doc using the library with React.

In any case, I'll provide a demo inside the `demo/` folder when I have some time. I'll keep the issue open for tracking. Thanks again for the ask.

**Comment by obetomuniz** [comment]
@encryptblockr You check the [Guides](https://github.com/zenorocha/clipboard.js/wiki/Guides), [react-clipboard.js](https://www.npmjs.com/package/react-clipboard.js) and/or others ways to use the library with react in the library [wiki](https://github.com/zenorocha/clipboard.js/wiki)?
