### ISSUE TITLE
Page hangs after copy the text

### ISSUE THREAD

**Issue by rixcapricorn** [zenorocha/clipboard.js#869]
I have used copy to clipboard in my page to copy some token. But after copying the text, after few seconds, page gets hang, modal pop up is automatically gone + toggle switch is lost (see in background page, enable/disable token toggle button), javascript events lost.

**Comment by obetomuniz** [comment]
Hey @rixcapricorn, thanks for reporting, I'm planning to contribute to some open issues. Can you confirm if your problem remains? For now, without a proposal demo to reproduce, I am closing the report since it seems a not related clipboard.js bug to me. You are welcome to re-open if including a reproducible demo using jsfiddle or something like that.
