### ISSUE TITLE
Client potential XSS - feedback needed

### ISSUE THREAD

**Issue by DanielRuf** [zenorocha/clipboard.js#871]
Please check and provide feedback, because so far I can not verify if there is really an issue / a vulnerability.

![grafik](https://github.com/zenorocha/clipboard.js/assets/827205/88ff4234-342c-4984-a242-e0b00f731373)

**Comment by obetomuniz** [comment]
@DanielRuf can you check if it still appears when using the latest version of the library? Also, can you please provide a reproducible environment to help me check this report? 

In any case, from what I understood, it seems a data sanitization issue, which is not a responsibility of clipboard.js from my perspective at first level, but with additional information, I can go deep into the investigation of your report, and if we find a related vulnerability, we can propose a solution to mitigate. 

For now, closing, since it is not using the latest version of the library. Feel free to re-open it if you reproduce it using the latest version.
