### ISSUE TITLE
Avoid serving legacy JavaScript to modern browsers @babel/plugin-transform-classes

### ISSUE THREAD

**Issue by mimoudix** [zenorocha/clipboard.js#872]
## 🐛 Bug Report

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/zenorocha/clipboard.js/blob/master/contributing.md)?

(Write your answer here.)

### Expected Behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

_Tip: Try to use screenshots, gifs, videos, always remember people better understand with a visual way._

### Actual Behaviour

Instead of '...', what I saw was that '...' happened instead.

### To Reproduce

(Write your steps such as:)

1. Step 1...
1. Step 2...
1. Step 3...

### Browsers Affected

I tested on all major browsers and only IE 11 does not work.

### Operational System

(Place here your Operational System.)

**Comment by Zardoz89** [comment]
I would add that actually doing a "import ClipboardJS from 'clipboard.min.js';" from the browser it's imposible. The webpack code that it's inserted, don't work on a currently normal javasript browser modules environment.

**Comment by obetomuniz** [comment]
Hi @mimoudix, the report is not concise. I'm planning to contribute to some open issues. Is it a bug or a proposal? Soon I will be triaging it, but before including it in the queue, can you provide more clarification around what problems this issue is solving?

For now, closing due to the lack of details. Please don't hesitate to re-open it after adding more details.
